events {}

http {
  upstream loki_write {
    server 192.168.28.135:3101;
    server 192.168.28.135:3102;
    server 192.168.28.135:3103;
  }

  upstream loki_read {
    server 192.168.28.136:3201;
    server 192.168.28.136:3202;
  }

  server {
    listen 3100;

    location = /ready {
      proxy_pass http://loki_read;
    }

    location = /loki/api/v1/push {
      proxy_pass http://loki_write;
    }

    location / {
      proxy_pass http://loki_read;
    }
  }
}
